In [3]:
import numpy as np



---


**Question 1**

In [39]:
# Create a 3x3 array with random integers between 1 and 100
array=np.random.randint(1,101,(3,3)) # Taking 101 because low is exclusive
print("Original Array:")
print(array)

# Transpose the array (interchange rows and columns)
transposed_array = array.T

print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[48 89 25]
 [ 6 45 70]
 [ 3 24 52]]

Transposed Array:
[[48  6  3]
 [89 45 24]
 [25 70 52]]




---
**Question 2**


In [ ]:
# Generate a 1D array with 10 elements
array_1d = np.arange(10)

print("Original 1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("\nReshaped into 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]




---
**Question 3**

In [ ]:
# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the 4x4 array, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode="constant", constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


Original 4x4 Array:
[[0.67495498 0.31619064 0.71085917 0.01786956]
 [0.51762101 0.098631   0.08987524 0.23985303]
 [0.68818213 0.34789203 0.74260685 0.40119803]
 [0.01293051 0.20302316 0.72346365 0.03084708]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.67495498 0.31619064 0.71085917 0.01786956 0.        ]
 [0.         0.51762101 0.098631   0.08987524 0.23985303 0.        ]
 [0.         0.68818213 0.34789203 0.74260685 0.40119803 0.        ]
 [0.         0.01293051 0.20302316 0.72346365 0.03084708 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]




---


**Question 4**

In [40]:
# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5) # taking 61 because stop is exclusive

print(array)

[10 15 20 25 30 35 40 45 50 55 60]



---
**Question 5**


In [ ]:
# NumPy array of given list of strings
string_array = np.array(['python','numpy','pandas'])

# Apply different case transformations
upper_case = np.char.upper(string_array)        # Convert to uppercase
lower_case = np.char.lower(string_array)        # Convert to lowercase
title_case = np.char.title(string_array)        # Convert to title case
capitalize_case = np.char.capitalize(string_array)  # Capitalize the first letter

# Print the results
print("Original Array:")
print(string_array)

print("\nUppercase:")
print(upper_case)

print("\nLowercase:")
print(lower_case)

print("\nTitle Case:")
print(title_case)

print("\nCapitalize:")
print(capitalize_case)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']




---


**Question 6**

In [ ]:
# Create a NumPy array of words
words = np.array(["apple", "banana", "cherry", "date", "elderberry"])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Print the results
print("Original Array of Words:")
print(words)

print("\nWords with Spaces Between Characters:")
print(spaced_words)


Original Array of Words:
['apple' 'banana' 'cherry' 'date' 'elderberry']

Words with Spaces Between Characters:
['a p p l e' 'b a n a n a' 'c h e r r y' 'd a t e' 'e l d e r b e r r y']




---
**Question 7**


In [41]:
# Create the two 2D NumPy arrays
array1 = np.array([[1, 2, 6], [4, 1, 3], [8, 4, 2]])
array2 = np.array([[6, 1, 3], [2, 5, 1], [3, 7, 1]])

# Perform element-wise addition
add = array1 + array2

# Perform element-wise subtraction
sub = array1 - array2

# Perform element-wise multiplication
mul = array1 * array2

# Perform element-wise division
div = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(add)

print("\nElement-wise Subtraction:")
print(sub)

print("\nElement-wise Multiplication:")
print(mul)

print("\nElement-wise Division:")
print(div)

Array 1:
[[1 2 6]
 [4 1 3]
 [8 4 2]]

Array 2:
[[6 1 3]
 [2 5 1]
 [3 7 1]]

Element-wise Addition:
[[ 7  3  9]
 [ 6  6  4]
 [11 11  3]]

Element-wise Subtraction:
[[-5  1  3]
 [ 2 -4  2]
 [ 5 -3  1]]

Element-wise Multiplication:
[[ 6  2 18]
 [ 8  5  3]
 [24 28  2]]

Element-wise Division:
[[0.16666667 2.         2.        ]
 [2.         0.2        3.        ]
 [2.66666667 0.57142857 2.        ]]




---


**Question 8**

In [42]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]




---


**Question 9**

In [28]:
# Generate an array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, 100)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Printing the results
print("Random Array:", random_array)
print("\nPrime Numbers:", prime_numbers)

Random Array: [583 807 450 286 914  28 688 244 218 210  18 539 284 660 959 135 384 956
 927 961 780 678 920 249 786 546 487 258 938 760 144 393 382 200 938 572
  64  28 471 469 248 470 959 703 913 440 196 636 961 678 311  22 403 104
 960 797 593  52 429   6 127 862   4 786 843 430 964 402 747  57 312 769
  54 515 790 115 867 622 254 784 503 164 122 977 757 130  98 882 799 902
 508 241 371 756  33 554 453 849 830 640]

Prime Numbers: [487, 311, 797, 593, 127, 769, 503, 977, 757, 241]




---


**Question 10**

In [38]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(0, 41, size=30)  # Temperatures between 0 and 40 degrees Celsius

# Reshape the array into weeks (4 full weeks and 2 remaining days)
weeks = np.zeros((5, 7))
weeks[:4, :7] = daily_temperatures[:28].reshape(4, 7)
weeks[4, :2] = daily_temperatures[28:]

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Display the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures for the Month: [40  7 38 18 36  5 37 34 16  1 12 35 23 20 12 11 20 23 24 14 23  9 33 24
 33  8  6  9 34 35]
Weekly Averages: [25.85714286 20.14285714 18.14285714 17.42857143  9.85714286]
